[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.25"

[rpc_endpoints]
local = "${LC_RPC_URL}"
sepolia = "${RPC_URL_REMOTE}"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
