[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.25"
rpc_url = "http://127.0.0.1:8545"


[profile.sepolia]
rpc_url = "${RPC_URL_REMOTE}"
etherscan_api_key = "${ETHERSCAN_API}"
private_key = "${PRIVATE_KEY}"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
